---
title: "P8105 Final Project: Alcohol-Related Liver Transplants"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Liver Transplants
Liver transplantation is a life-saving therapy for patients with end-stage liver disease, and Alcohol-Associated Liver Disease (ALD) has become one of its leading indications in the United States. As ALD-related morbidity and mortality continue to rise, understanding patterns in transplant access, candidate characteristics, and post-transplant outcomes has become increasingly important.

Our project utilizes data from the Scientific Registry of Transplant Recipients (SRTR), which compiles detailed information from transplant programs across the United States, including data collected through the United Network for Organ Sharing (UNOS). The SRTR serves as a national registry that captures comprehensive demographic, clinical, and outcome data on all transplant candidates, recipients, and donors. For this study, we restricted our cohort to adult patients (aged 18 years or older) who underwent transplantation from 2020 onward, reflecting recent shifts in clinical practice and the introduction of early liver transplantation for patients with severe alcohol-associated liver disease, particularly those presenting with acute alcoholic hepatitis.

SRTR make all data available to the public while honoring patient privacy. The data dictionary with all available variables can be found [here](https://www.srtr.org/requesting-srtr-data/saf-data-dictionary/).

In this website, we provide an overview of key aspects of liver transplantation. Each link has a different focus of liver transplantation, highlighting trends in candidate demographics, donor demographics, transplant rates, and post-transplant outcomes. Our goal is to offer an accessible, data-driven perspective on the evolving role of ALD in liver transplantation.

## Subsection 1
text/code


## Links to Pages within Sites

### Page 1
Brief description of page1. 
[page1](page1.html)

### Waitlist Characteristics and Mortality
This page includes an additional dataset comprising all patients listed for transplant. It summarizes demographic and clinical characteristics of adults listed for liver transplantation with alcohol-related liver disease, comparing acute alcohol-related hepatitis and alcohol-related cirrhosis. It presents sex-stratified descriptive statistics, highlights differences in age, MELD score, and racial/ethnic distribution, and reports waitlist mortality and follow-up times. The page also includes Kaplan–Meier curves illustrating waitlist survival patterns across subgroups. Click here to learn more: [Waitlist](page2.html).

### Page 3
Brief description of page3. 
[page3](page3.html)

### Page 4
Brief description of page4. 
[page4](page4.html)


